spring:
  application:
    # 服务名
    name: server-consumer-feign-sentinel
  cloud:
    nacos:
      discovery:
        #服务注册中心
        server-addr: 127.0.0.1:8848
    #熔断限流
    sentinel:
      transport:
        dashboard: 127.0.0.1:8888

#开启 Feign 对 Sentinel 的支持
feign:
  sentinel:
    enabled: true

server:
  # 服务端口
  port: 8183

management:
  # 端点检查（健康检查）
  endpoints:
    web:
      exposure:
        include: "*"